export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES';
export const SAVE_EMPLOYEE = 'SAVE_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS';
